const GET_TICKERS_SUCCESS = 'tickers/GET_TICKERS_SUCCESS'
const GET_TICKERS_ERROR = 'tickers/GET_TICKERS_ERROR'
const ADD_LAST_PRICE_SUCCESS='lastPrice/ADD_LAST_PRICE_TICKERS'
const ADD_LAST_PRICE_ERROR='lastPrice/ADD_LAST_PRICE_ERROR'

export {
    GET_TICKERS_SUCCESS,
    GET_TICKERS_ERROR,
    ADD_LAST_PRICE_SUCCESS,
    ADD_LAST_PRICE_ERROR,
}
